version: '3.0'

services:
  run_with_me:
    container_name: run_with_me
    image: run_with_me:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env.${FLASK_ENV}
    volumes:
      - ./:/app
    command: 'python main.py'
    ports:
      - '80:5000'
